- name: mysql
  hosts: mysql
  become: yes 
  tasks: 
  
  - name: disable mysql
    ansible.builtin.package:
      name: mysql
      state: absent

  - name: setup MySQL 5.7 repo 
    ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

  - name: install mysql community server
    ansible.builtin.package:
      name: mysql-community-server
      state: present 

  - name: enable and start mysql
    ansible.builtin.service:
      name: mysqld
      state: restarted
      enabled: yes

  - name: setup root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
