- name: user
  hosts: user
  become: yes 
  tasks:
  - name: disable old nodejs and enable nodejs:18
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
 
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  
  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: create directory
    ansible.builtin.file:
      path: /app
      state: directory
 
  - name: download user application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp 
    
  - name: unzip user application
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: Inastall dependances
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: copy user service file 
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service  

  - name: daemond reload and enable start user
    ansible.builtin.systemd_service:
      daemon_reload: true
      
  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo 
  
  - name: Install mongodb client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present

  - name: get the categories count
    ansible.builtin.command:  mongo --host mongodb.devopsaws.site --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
    register: user_count

  # - name: print the count
  #   ansible.builtin.debug:
  #     msg: "product count: {{user_count}}"

  - name: load user data
    ansible.builtin.command: mongo --host mongodb.devopsaws.site < /app/schema/user.js
    when: product_count.stdout == "0" # keep double quotes

  - name: start and enable user
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes